SELECT DISTINCT Nome_Local --seleciona apenas os que nao sao repetidos devido ao DISTINCT
FROM Lugar;

/*
Resultado da consulta:
Agarra que é ladrão (Covilhã)
Alvito (Boidobra)
Anfiteatro (Covilhã)
Angry ones (Covilhã)
Antena (Serra da Estrela)
Atravessar a EN339 
Barreira (Vila do Carvalho)
Barroca Grande (Aldeia de São Francisco de Assis)
Boidobra (Boidobra)
Bouça (Cortes do Meio)
Calvário (Covilhã)
Caminho
Caminho (Covilhã)
Canhoso (Teixoso)
Cantar-Galo (Cantar-Galo)
Capela (Covilhã)
Capela do Calvário (Covilhã)
Casal de Santa Terezinha (São Jorge da Beira)
Centro de Limpeza de Neves (Piornos Serra da Estrela)
Cortes de Cima (Cortes do Meio)
Covilhã (Conceição)
Covilhã (Santa Maria)
Covilhã (São Martinho)
Covilhã (São Pedro)
Crânio (Covilhã)
Criança (Covilhã)
Curral, (Serra da Estrela)
Direção a seguir
Dragão (Covilhã)
Elevador (Covilhã)
Elevador das 164 escadas (Covilhã)
Elevador São João (Covilhã)
Empresa de Lãs (Covilhã)
Enfermeira (Covilhã)
Erada (Erada)
Escadaria junto ao elevador da Goldra (Covilhã)
Escadaria junto ao elevador de Sto.André (Covilhã)
Estádio Municipal José Santos Pinto (Covilhã)
Fábricas (Covilhã)
Fim (Serra da Estrela)
Flores (Covilhã)
Fonte
Fonte (Covilhã)
Funil dos Conchos (Serra da Estrela)
Gnammas ou Oriçangas (Serra da Estrela)
Igreja (Covilhã)
Igreja de Santa Maria Maior (Covilhã)
Igreja Santa Maria (Covilhã)
Inicío (Serra da Estrela)
Jardim (Covilhã)
Jardim da Goldra (Covilhã)
Jardim do Lago (Covilhã)
Ladeira Grande (Tortosendo)
Lagoa Comprida (Serra da Estrela)
Lagoa da Ribeira da Nave da Areia (Serra da Estrela)
Lagoa do Covão do Forno (Serra da Estrela)
Lagoa do Covão dos Conchos (Serra da Estrela)
Lagoa Redonda (Serra da Estrela)
Lagoa Seca (Serra da Estrela)
Mariola do Alto da Pedrice (Serra da Estrela)
Mariola do Poio da Cabeça (Serra da Estrela)
Miradouro das Portas do Sol (Covilhã)
Mocho (Covilhã)
Orjais (Orjais)
Palacete (Covilhã)
Parque da Goldra (Covilhã)
Parque Pedonal do Rodrigo (Covilhã)
Pássaro (Covilhã)
Paul (Paul)
Penhas da Saúde (Cortes do Meio)
Penhas da Saúde (Serra da Estrela)
Peso (Peso)
Pintura (Covilhã)
Pintura da Cidade (Covilhã)
Piscina Municipal (Covilhã)
Poço (Covilhã)
Poio dos Vales (Serra da Estrela)
Ponte (Covilhã)
Ponte Mártir-in-Colo (Covilhã)
Ponto de informação
Ponto de informação (Covilhã)
Ponto de informação do PR12CVL (Covilhã)
Pormenor da paisagem (Serra da Estrela)
Portela (Vila do Carvalho)
Praça do Município (Covilhã)
Relógio de Sol (Covilhã)
Relvas (Ourondo)
Ribeiro da Água Fria e Fragão das Meadas (Serra da Estrela)
Rotunda do rato (Covilhã)
Ruinas da Estação de Teleférico (Serra da Estrela)
Sarzedo (Sarzedo)
Seguir à direita deixando o estradão
Seguir à direita pelo estradão
Seguir à esquerda
Seguir à esquerda depois do depósito
Soldado Desconhecido (Covilhã)
Teixoso (Teixoso)
Terlamonte (Teixoso)
Terra da Senhora (Unhais da Serra)
Tetas (Covilhã)
Torre (Covilhã)
Tortozendo (Tortosendo)
Trigais (Erada)
Um dos ribeiros que formará a Ribeira da Goldra
Unhais da Serra (Unhais da Serra)
Vale da Cerdeira (São Jorge da Beira)
Vale das Donas (Tortosendo)
Vale do Fragão das Meadas e curral (Serra da Estrela)
Vale Glaciar de Alforfa e Cascalheira do Diabo (Serra da Estrela)
Vales do Rio (Vales do Rio)
Varanda dos Carqueijais
Velhote (Covilhã)
Vértice Geodésico da Varanda (Serra da Estrela)
Vértice Geodésico do Cascalvo (Serra da Estrela)
Vhils (Covilhã)
Vila do Carvalho (Vila do Carvalho)
Vista da Lagoa Comprida (Serra da Estrela)
Vista das Estendedeiras (Covilhã)
Vista para o Picoto (Covilhã)

*/