# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wElPxiZp6bNeyyy-VQaVdbQK9xjoUxid
"""

# **Ficha 2**

#import wave
import matplotlib.pyplot as plt
import numpy as np

from scipy.io import wavfile

# https://ipython.org/ipython-doc/stable/api/generated/IPython.display.html
# Para testar o Audio
from IPython.display import Audio, display
framerate = 44100
t = np.linspace(0,5,framerate*5)
data = np.sin(2*np.pi*220*t) + np.sin(2*np.pi*224*t)
Audio(data,rate=framerate)

# 1 - Ler os ficheiros de áudio 'bass.wav', 'guitar.wav', 'drums.wav'."""

"""from google.colab import drive
#drive.mount('/content/drive')

sample_freq_bass, bass = wavfile.read('/content/drive/MyDrive/Colab Notebooks/Audios/bass.wav')

sample_freq_guitar, guitar = wavfile.read('/content/drive/MyDrive/Colab Notebooks/Audios/drums.wav')

sample_freq_drums, drums = wavfile.read('/content/drive/MyDrive/Colab Notebooks/Audios/guitar.wav')"""

# 2 - Verificar a frequência de amostragem de cada um dos áudio.

print('numero de amostras por segundo do bass:', sample_freq_bass)

print('numero de amostras por segundo do guitar:', sample_freq_guitar)

print('numero de amostras por segundo do drums:', sample_freq_drums)

L, = bass.shape
print(L)

print(bass.size, bass.shape)

# 3 - Verificar a duração em segundos de cada áudio.

n_samples_bass = bass.size
print('numero total de amostras bass:', n_samples_bass)

duration_bass = n_samples_bass/sample_freq_bass
print('duração do audio bass (segundos):', duration_bass)

n_samples_guitar = guitar.size
print('numero total de amostras guitar:', n_samples_guitar)

duration_guitar = n_samples_guitar/sample_freq_guitar
print('duração do audio guitar (segundos):', duration_guitar)

n_samples_drums = drums.size
print('numero total de amostras guitar:', n_samples_guitar)

duration_drums = n_samples_drums/sample_freq_drums
print('duração do audio drums (segundos):', duration_drums)

#Ex 4 - Selecione o segundo 12 do audio drum

drums_12 = drums[11*sample_freq_drums: 12*sample_freq_drums]
np.size(drums_12)

#Ex 5 - Criar uma nova variavel com audio selecionado na alınea anterior, mas repetido 4 vezes
drums_12_repetido = np.concatenate((drums_12, drums_12, drums_12, drums_12))
print(np.size(drums_12_repetido))

#Ex 6 - Seleccione os ´audios ’bass.wav’, ’guitar.wav’, ’drums.wav’ entre o segundo 10 e o segundo 20 e
##cria novas vari´aveis (rum seg, guitar seg e bass seg ) com cada uma das sele¸c˜oes.

bass_seg = bass[9*sample_freq_bass: 19*sample_freq_bass]
guitar_seg = guitar[9*sample_freq_guitar: 19*sample_freq_guitar]
drums_seg = drums[9*sample_freq_drums: 19*sample_freq_drums]

#Ex 7. Represente cada um dos sons
display(Audio(bass_seg, rate=sample_freq_bass))
display(Audio(guitar_seg, rate=sample_freq_guitar))
display(Audio(drums_seg, rate = sample_freq_drums))

#Ex 8 - Represente cada um dos sons alterando a frequˆencia para o dobro
dobro_bass = 2 * sample_freq_bass
dobro_guitar = 2 * sample_freq_guitar
dobro_drums = 2 * sample_freq_drums
display(Audio(bass_seg, rate = dobro_bass))
display(Audio(bass_seg, rate = dobro_guitar))
display(Audio(bass_seg, rate = dobro_drums))

#Ex 9 - Aumente as amplitudes do segmento bass seg (ex. bass seg*2). Represente o resultado
amp_bass = bass_seg * 2
display(Audio(amp_bass, rate = sample_freq_bass))
amp_guitar = guitar_seg * 2
display(Audio(amp_guitar, rate = sample_freq_guitar))
amp_drums = drums_seg * 2
display(Audio(amp_drums, rate = sample_freq_drums))

#Ex 10 - Diminua as amplitudes do segmento guitar seg (ex. guitar seg*0.15). Represente o resultado
dim_bass = bass_seg * 0.15
display(Audio(dim_bass, rate = sample_freq_bass))
dim_guitar = guitar_seg * 0.15
display(Audio(dim_guitar, rate = sample_freq_guitar))
dim_drums = drums_seg * 0.15
display(Audio(dim_drums, rate = sample_freq_drums))

#Ex 11 -  Combine os ´audios drum seg e guitar seg (drum seg+guitar seg). Represente o resultado.
combinar = bass_seg + guitar_seg
Audio(combinar, rate = sample_freq_bass)

#Ex 12 - Combine agora os trˆes segmentos (drum seg+guitar seg+bass seg). Represente o resultado
combinar_3 = bass_seg + guitar_seg + drums_seg
Audio(combinar_3, rate = sample_freq_bass)

#Ex 13 - Fa¸ca uma nova combina¸c˜ao com os trˆes segmentos, mas com as novas amplitudes alteradas
#nas al´ıneas anteriores

combinar_amp = amp_bass + amp_guitar + amp_drums
Audio(combinar_amp, rate = sample_freq_bass)

#Ex 14 Verifique como ficam os plots de cada um dos ´audios criados na al´ınea anterios

#ORIGINAL

plt.figure(figsize=(10, 2))
plt.plot(bass_seg, color='blue')
plt.title("Bass")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(guitar_seg, color='orange')
plt.title("Guitar")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(drums_seg, color='green')
plt.title("Drums")
plt.show()

#Ex 14 - DOBRO FREQUENCIA

plt.figure(figsize=(10, 2))
plt.plot(dobro_bass, color='blue')
plt.title("Bass")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(dobro_guitar, color='orange')
plt.title("Guitar")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(dobro_drums, color='green')
plt.title("Drums")
plt.show()

# Ex 14 - ampplitudo dobrada
plt.figure(figsize=(10, 2))
plt.plot(amp_bass, color='blue')
plt.title("Bass")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(amp_guitar, color='orange')
plt.title("Guitar")
plt.show()

plt.figure(figsize=(10, 2))
plt.plot(amp_drums, color='green')
plt.title("Drums")
plt.show()