# -*- coding: utf-8 -*-
"""aula01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrKbj80166MozYYgnNTY_e1c3UkBA4ZF

| Instante $t$ (s) | Valor Exato de $t$ | Amostra $m(t)$ | Valor Quantizado ($q_k$) | Nível Decimal | Palavra Binária (4 bits) |
| --- | --- | --- | --- | --- | --- |
| $\frac{1}{8}$ | $0.1250$ | $4.2426$ | ($\frac{9}{2}$) | $13$ | `1101` |
| $\frac{3}{8}$ | $0.3750$ | $4.2426$ | ($\frac{9}{2}$) | $13$ | `1101` |
| $\frac{5}{8}$ | $0.6250$ | $-4.2426$ | ($-\frac{9}{2}$) | $2$ | `0010` |
| $\frac{7}{8}$ | $0.8750$ | $-4.2427$ | ($-\frac{9}{2}$) | $2$ | `0010` |
"""

"""exercicio 1"""
import numpy as np
import matplotlib.pyplot as plt


t = np.arange(1/8, 1.1, 2/8)
print('Tempo: ', t)
m = 6*np.sin(2*np.pi*t)
print('Amostras: ', m)
plt.plot(t,m)
plt.show()

"""exercicio 2"""
import numpy as np
import matplotlib.pyplot as plt


t = np.arange(1/8, 1.1, 1/8)
print('Tempo: ', t)
m = 6*np.sin(2*np.pi*t)
print('Amostras: ', m)
plt.plot(t,m)
plt.show()

"""exercicio 3"""

import numpy as np
import matplotlib.pyplot as plt


t = np.arange(1/8, 1.1, 1/16)
print('Tempo: ', t)
m = 6*np.sin(2*np.pi*t)
print('Amostras: ', m)
plt.plot(t,m)
plt.show()

"""'''EXERCICIO 4'''

Temos do exericico 3 que a amplitude total é 12, 4 bits entao 2^4 = 16
então o erro de quantização é 12/16 = 3/4
Do exericicio 4 usamos 5 bits entao  temos 2^5 = 32 , logo o erro de quantizaçao é 12/32 = 3/8

aumento o numero de bits , aumentamos o numero de intervalo e o erro de quantizaçao será menor neste caso passou para metade

(3/4)/(3/8) = 2
"""

"""exercicio 5"""
import numpy as np
import matplotlib.pyplot as plt


t = np.arange(1/8, 1.1, 1/8)
print('Tempo: ', t)
m = 2*np.sin(2*np.pi*t)
print('Amostras: ', m)
plt.plot(t,m)
plt.show()

"""EXERCICIO 5

| Instante $t$ (s) | Amostra $m(t)$ | Valor Quantizado |
| --- | --- | --- |
| $\frac{1}{8}$ | $1.4142$ | $\frac{5}{4} = 1.2500$ |
| $\frac{2}{8}$ | $2.0000$ | $\frac{7}{4} = 1.7500$ |
| $\frac{3}{8}$ | $1.4142$ | $\frac{5}{4} = 1.2500$ |
| $\frac{4}{8}$ | $0.0000$ | $0.0000$ |
| $\frac{5}{8}$ | $-1.4142$ | $-\frac{5}{4} = -1.2500$ |
| $\frac{6}{8}$ | $-2.0000$ | $-\frac{7}{4} = -1.7500$ |
| $\frac{7}{8}$ | $-1.4142$ | $-\frac{5}{4} = -1.2500$ |
| $\frac{8}{8}$ | $0.0000$ | $0.0000$ |
"""