# -*- coding: utf-8 -*-
"""Aula03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9FtPltym8C3x6AKkPqehjqhWsbqa9l-
"""

#---------------------------------------
#Ficha 3

from matplotlib import pyplot as plt
#import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


#---------------------------------------
#Ficha 3  - Ex 2

# Le  entre 0 e 255
image = Image.open('/content/Rosa1024.png')
arr = np.asarray(image) #Cria um objeto numpy
plt.imshow(arr, cmap='gray', vmin=0, vmax=255)
plt.show()
print(arr.shape)
print(arr.dtype)

image_Cor = Image.open('/content/monarch.ppm')
arr_Cor = np.asarray(image_Cor)
plt.imshow(arr_Cor)
plt.show()
print(arr_Cor.shape)
print(arr_Cor.dtype)

#Debito


bits_rosa = bytes_rosa * 8
kb_rosa = bytes_rosa / 1024

print("Rosa1024.png")
print(f"Bits:   {bits_rosa:,} ")
print(f"Bytes:  {bytes_rosa:,} ")
print(f"KB:     {kb_rosa:.2f} \n")


bits_monarch = bytes_monarch * 8
kb_monarch = bytes_monarch / 1024

print("monarch.ppm")
print(f"Bits:   {bits_monarch:,}")
print(f"Bytes:  {bytes_monarch:,}")
print(f"KB:     {kb_monarch:.2f}")

#3. Espelho horizontal e espelho vertical.
espelho_horizontal = arr[:, ::-1]
plt.imshow(espelho_horizontal, cmap='gray', vmin=0, vmax=255)
plt.show()

espelho_vertical = arr[::-1, :]
plt.imshow(espelho_vertical, cmap='gray', vmin=0, vmax=255)
plt.show()

#4. Redu¸c˜ao da imagem para metade das linhas e das colunas.
metade_linhas = arr[::2, :]
plt.imshow(metade_linhas, cmap='gray', vmin=0, vmax=255)
plt.show()

metade_colunas = arr[:, ::2]
plt.imshow(metade_colunas, cmap='gray', vmin=0, vmax=255)
plt.show()

#5. Amplia¸c˜ao da imagem para o dobro de linhas e colunas.
L,C = np.shape(arr)
dobro = np.zeros_like(arr, shape = (2*L,2*C))
dobro[::2, ::2] = arr
dobro[1::2, ::2] = arr
dobro[::2, 1::2] = arr
dobro[1::2, 1::2] = arr
plt.imshow(dobro, cmap='gray', vmin=0, vmax=255)
plt.show()

#6. Corte do bloco central com 200 linhas e 200 colunas
corte = arr[400:600: , 400:600: ]
plt.imshow(corte, cmap='gray', vmin=0, vmax=255)
plt.show()

#7. Inser¸c˜ao de um bloco de uma imagem, noutra imagem
arr1[0:200:, 0:200:] = corte
plt.imshow(arr1, cmap='gray', vmin=0, vmax=255)
plt.show()

#8. Calculo do negativo de uma imagem
rosa_neg = 255 - arr
plt.imshow(rosa_neg, cmap='gray', vmin=0, vmax=255)
plt.show()

#9. Rota¸c˜ao de 90 graus.
rot_rosa = arr[::].T
plt.imshow(rot_rosa, cmap = 'gray' , vmin=0 , vmax=255)
plt.show()

#Calcule o histograma de n´ıveis de cinzento (histogram
plt.figure(figsize=(3,3))
vals = arr.flatten()
hist, bins, patches = plt.hist(vals,32)
plt.xlim([0,255])
plt.show()

#Calcule o histogram normalizado
N,M = arr.shape
totalpxl = N*M
hist_norm = hist / totalpxl
plt.figure(figsize=(3,3))
plt.plot(hist_norm)

#Calcule o histograma acumulado